### ISSUE TITLE
Improve Stationary website 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Cool-Front-End_Templates#100]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
@Skapsime would you like to work on this ?

**Comment by Skapsime** [comment]
yes absolutely

**Comment by arpit456jain** [comment]
@Skapsime go ahead
