### ISSUE TITLE
link preview images in home page

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Cool-Front-End_Templates#105]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
@jigar-sable may I assign you this ?

**Comment by jigar-sable** [comment]
Yeah Sure..

**Comment by arpit456jain** [comment]
If you want you can make these changes in my other two repos also

**Comment by arpit456jain** [comment]
although I can't give lvl3 in both of them but i will surely give lvl2

**Comment by jigar-sable** [comment]
@arpit456jain alright will be doing the same soon for CSS & JS repos.

**Comment by arpit456jain** [comment]
> @arpit456jain alright will be doing the same soon for CSS & JS repos.
> No worries regarding levels.

that's cool man 🎉  I appreciate

**Comment by jigar-sable** [comment]
Thanks @arpit456jain
