### ISSUE TITLE
some images are not rendering 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Cool-Front-End_Templates#107]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
@jigar-sable great work its looking so cool but some images are not rendering please check

https://deploy-preview-106--cool-front-end-templates.netlify.app/?utm_source=github&utm_campaign=bot_dp

**Comment by jigar-sable** [comment]
Yeah few of them aren't working. Need to rename & few changes.
