### ISSUE TITLE
Add a gif of home page in read me

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Cool-Front-End_Templates#109]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by jigar-sable** [comment]
I would like to work on this issue.
