### ISSUE TITLE
Improve Ui of Artica template in Desktop view and if possible mobile view also 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Cool-Front-End_Templates#110]
## Issue Type:

- [x] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

![image](https://user-images.githubusercontent.com/55352601/126973050-cdcd74af-38b8-4648-91bf-9c22bd64974a.png)

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
@Skapsime can you do this?

**Comment by sidparashar2001** [comment]
right now the condition is not that good I will try my best and I will also remove the :active class because it's the main root of problem.
 Assign it to me
