### ISSUE TITLE
improve UI of simple Portfolio template 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Cool-Front-End_Templates#111]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

![image](https://user-images.githubusercontent.com/55352601/126973873-92b93666-a0b1-469f-b33d-2e410067638a.png)

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Skapsime** [comment]
can I work on this ??

**Comment by arpit456jain** [comment]
Sure @Skapsime

**Comment by Skapsime** [comment]
t

> Sure @Skapsime
Thanks for assign me on this project
