### ISSUE TITLE
Back to top button on homepage

### ISSUE THREAD

**Issue by jigar-sable** [arpit456jain/Cool-Front-End_Templates#112]
## Issue Type:

- [x] Feature Request

## **Describe the feature**

Add scroll top button on homepage.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
@jigar-sable you want to work on this ?

**Comment by jigar-sable** [comment]
@arpit456jain yes assign me
