### ISSUE TITLE
Responsive Login Sigh up page Template

### ISSUE THREAD

**Issue by tany1014** [arpit456jain/Cool-Front-End_Templates#118]
Responsive Login sighup system @arpit456jain @ankitapuri  under DCP21

**Comment by arpit456jain** [comment]
@tany1014 go ahead and complete it asap

**Comment by arpit456jain** [comment]
@tany1014 any updates ?

**Comment by aditya687** [comment]
Can I try this issue @arpit456jain ?

**Comment by tany1014** [comment]
yes i have finished whit my work

**Comment by arpit456jain** [comment]
@tany1014 kindly make PR asap

**Comment by arpit456jain** [comment]
and @aditya687 you can also make a PR for this issue since your design will be different so it will not create any problem

**Comment by aditya687** [comment]
Okk, thanks
