### ISSUE TITLE
Yoga Template Landing page UI &  Code snippet improvement!

### ISSUE THREAD

**Issue by SAHU-01** [arpit456jain/Cool-Front-End_Templates#124]
## Issue Type:

- [*] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**
 The Yoga templete Landing page UI needs to be fixed and the code has to be edited so that the website looks better!
- A clear and concise description of what the bug is.
<img width="926" alt="yoga" src="https://user-images.githubusercontent.com/71656941/127671007-97d5873e-1cce-4b2f-88e1-e71274a0f28b.png">
 the alignment and UI isn't proper
## **Possible solution**

- Describe the solution you thought of.
 
Changing the UI to a more user interractive one and amending the existent code snippets for better performance
## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/71656941/127671171-36076cb7-bf8b-4886-9d83-eee2fe276bab.png)
even the contact us section needs to be fixed so that the webpage looks more meaningful!

**Comment by arpit456jain** [comment]
@SAHU-01 go ahead

**Comment by SAHU-01** [comment]
These are the  ideas I would suggest for the template,Whichever you choose I'll customize the webpage accordingly,plz let me know which design suits your taste!
![image](https://user-images.githubusercontent.com/71656941/127732042-03f54163-2ab0-455b-879a-2b48f60b2809.png)
![image](https://user-images.githubusercontent.com/71656941/127732056-59583ea3-f22e-49dc-a00d-b14b3b656bb7.png)

**Comment by arpit456jain** [comment]
Hey @SAHU-01 do one thing first improve the ui of this current yoga template little bit as you have explained in the issue and make a PR for it..
I will give it a lvl2

Then create a new issue and under that issue you can add this design as a new project 
I will give it a lvl3 

Hope you understand

**Comment by SAHU-01** [comment]
Ok got it!
