### ISSUE TITLE
Add some badges to the README

### ISSUE THREAD

**Issue by Umesh-01** [arpit456jain/Cool-Front-End_Templates#129]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [x] Documentation

## **Describe the bug**
Add some badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

## **Possible solution**
I will add some badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.

- [ ] Will add some more badges
- [ ] Will align them to center
- [ ] Will link them to related webpages/sections

## **Sample Image**

![image](https://user-images.githubusercontent.com/83420185/128010895-3e0c0994-f3fe-4eca-bd85-9b9944aeb8cf.png)

**Comment by arpit456jain** [comment]
@Umesh-01 go ahead and complete it asap
