### ISSUE TITLE
New Yoga template(revised design and Code)

### ISSUE THREAD

**Issue by SAHU-01** [arpit456jain/Cool-Front-End_Templates#130]
## Issue Type:

- [ ] Bug Report
- [ * ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

Designing and writing source code for the yoga template

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
@SAHU-01 go ahead

**Comment by SAHU-01** [comment]
Kindly take a look at the website template now,if it suits your taste then,I'd proceed with the pr!
![image](https://user-images.githubusercontent.com/71656941/128489231-1b3b01ad-01bc-42e1-a4d2-2270b89c27ae.png)
![image](https://user-images.githubusercontent.com/71656941/128489267-657f58be-30f0-4c7b-86c3-661486bff6ee.png)
![image](https://user-images.githubusercontent.com/71656941/128489302-b6c062d6-1d6f-434e-8de7-10f46498767b.png)
![image](https://user-images.githubusercontent.com/71656941/128489325-f11755ec-964a-4ad1-8689-70c341271231.png)
![image](https://user-images.githubusercontent.com/71656941/128489363-e5e21748-8213-48f4-a864-48fc386cc024.png)
![image](https://user-images.githubusercontent.com/71656941/128489390-2b70a928-518d-4027-a15d-682afff0596c.png)

**Comment by arpit456jain** [comment]
Yeah @SAHU-01 its amazing 🔥👌

**Comment by SAHU-01** [comment]
> Yeah @SAHU-01 its amazing 🔥👌

ok then, i'll move ahead with the pr now!
