### ISSUE TITLE
make Yoga template 2 responsive 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Cool-Front-End_Templates#133]
## Issue Type:

- [x] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![screencapture-cool-front-end-templates-netlify-app-yoga-template-2-2021-08-06-19_47_48](https://user-images.githubusercontent.com/55352601/128524233-7c3469b9-0ae2-4059-bccd-2ef0acec09c8.png)

**Comment by arpit456jain** [comment]
@SAHU-01 you want to work on this ? level can be increased on the basis of work

**Comment by Anubhavdxt** [comment]
Hey @arpit456jain 
I would like to work on this issue, can you help me out with the details and how can I go ahead.

**Comment by arpit456jain** [comment]
@Anubhavdxt join the discord server and lets discuss about it in it , link is in the read me at last
