### ISSUE TITLE
Food Odering Template Feature Improvment

### ISSUE THREAD

**Issue by SAHU-01** [arpit456jain/Cool-Front-End_Templates#144]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.
The Food odering template page isn't visually attractive,the content isn't clear , a new UI can be made that's more legible and user friendly.Especially the client and footer section...

## **Possible solution**
- Describe the solution you thought of.

A UI similar to this for the template can be adopted to make it more visually attractive...

![image](https://user-images.githubusercontent.com/71656941/130081842-1305278b-6404-4881-baec-936499460d4f.png)

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/71656941/130082162-07a1dae6-c0ed-40c2-a79e-1530ceca618b.png)

**Comment by arpit456jain** [comment]
@SAHU-01 go ahead add this as a new template

**Comment by SAHU-01** [comment]
Sure!
