### ISSUE TITLE
Add GitHub bot for greetings

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Cool-Front-End_Templates#3]

**Comment by harshithatnbr** [comment]
I would like to work on this issue. Please assign it to me under DCP2021 . Thankyou.

**Comment by arpit456jain** [comment]
@harshithatnbr This project is not not registered in DCP2021 I just share this so that beginners can try to contribute so that they feel comfortable because when i participated in GSSOC'21 I was very confused how to start

**Comment by arpit456jain** [comment]
@harshithatnbr if you still want to contribute then please let me know open source is not limited to any program :)
happy coding !!

**Comment by harshithatnbr** [comment]
Even I am very new to open source. I would like to work on this issue.

**Comment by arpit456jain** [comment]
great @harshithatnbr go ahead :)

**Comment by arpit456jain** [comment]
if you need any help then let me know

**Comment by harshithatnbr** [comment]
Thankyou.
