### ISSUE TITLE
I wish to add a TO-DO List

### ISSUE THREAD

**Issue by ushmita4** [arpit456jain/Cool-Front-End_Templates#52]
I wish to create a TODO list.

**Comment by arpit456jain** [comment]
hey @ushmita4 are you dcp contribtuor ?

**Comment by ushmita4** [comment]
> hey @ushmita4 are you dcp contribtuor ?

Yes

**Comment by arpit456jain** [comment]
ok @ushmita4 
dont you think its related to js 

kindly create this issue on 
https://github.com/arpit456jain/Amazing-Js-Projects

and close this one I will assign u asap
