### ISSUE TITLE
Working on Food Corner website 

### ISSUE THREAD

**Issue by Sanju-github002** [arpit456jain/Cool-Front-End_Templates#56]
I want to add footer in website to give social accounts address and about us information.

Can I work on this ????

**Comment by arpit456jain** [comment]
hey @Sanju-github002  are you dcp contribtuor ?

**Comment by Sanju-github002** [comment]
Yess

**Comment by arpit456jain** [comment]
ok @Sanju-github002 go ahead :)

**Comment by Sanju-github002** [comment]
> ok @Sanju-github002 go ahead :)

Okay Thank you :)

**Comment by Sanju-github002** [comment]
<img width="946" alt="Screenshot 2021-07-14 105915" src="https://user-images.githubusercontent.com/78341083/125567834-ca02e74d-3b87-4537-abff-a1e680eb740a.png">


is this okkk

**Comment by arpit456jain** [comment]
Is it responsive @Sanju-github002 ?

**Comment by Sanju-github002** [comment]
> Is it responsive @Sanju-github002 ?

Yes it is responsive sir

**Comment by arpit456jain** [comment]
Make PR @Sanju-github002

**Comment by Sanju-github002** [comment]
<img width="252" alt="Screenshot 2021-07-14 111407" src="https://user-images.githubusercontent.com/78341083/125569621-a5dd15fc-821d-463f-add1-b5d98483a5d5.png">


see sir

**Comment by Sanju-github002** [comment]
How I upload img can you help me

**Comment by arpit456jain** [comment]
> How I upload img can you help me

You mean how to set IMG in background of page?

**Comment by arpit456jain** [comment]
@ankitapuri please help him

**Comment by Sanju-github002** [comment]
> > How I upload img can you help me
> 
> You mean how to set IMG in background of page?

Means how I upload my footer background to img folder in github

**Comment by arpit456jain** [comment]
See @Sanju-github002 fork this repo and clone it on your system then make nesscary Changes and add images in folder and make a PR from a new branch

**Comment by Sanju-github002** [comment]
Okay
