### ISSUE TITLE
Glassmorphic Profile Card

### ISSUE THREAD

**Issue by kiruba-r11** [arpit456jain/Cool-Front-End_Templates#70]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Possible solution**

It is a glassmorphic profile card, which can be used to describe us, our skills, and our achievements.

## **Screenshots**
<img width="1420" alt="Screenshot 2021-07-15 at 12 19 49 PM" src="https://user-images.githubusercontent.com/76843281/125742166-8ad823a9-c7ba-4fb1-92d2-ab36d1a03cb7.png">

**Comment by kiruba-r11** [comment]
@ankitapuri @arpit456jain I would like to work on this as a part of DCP'21

**Comment by arpit456jain** [comment]
@kiruba-r11 go ahead
