### ISSUE TITLE
Maroom - Interior Design Landing Page

### ISSUE THREAD

**Issue by kiruba-r11** [arpit456jain/Cool-Front-End_Templates#74]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Possible solution**

- This is a Landing Page for an Interior Design Product name Maroom. This was inspired by a random dribble mockup design.

## **Screenshots**

<img width="500" alt="Screenshot 2021-07-15 at 5 21 20 PM" src="https://user-images.githubusercontent.com/76843281/125783692-a88a1cec-91c0-4b6d-8fef-751c32211880.png">
<img width="501" alt="Screenshot 2021-07-15 at 5 21 31 PM" src="https://user-images.githubusercontent.com/76843281/125783698-f308c993-352d-4c69-8cfc-ef6c074fcd51.png">

**Comment by kiruba-r11** [comment]
@arpit456jain @ankitapuri I would like to work on this as a part of DCP'21

**Comment by arpit456jain** [comment]
ok @kiruba-r11 just make sure that you make it by your self dont download from anywhere 
we noticed these kinds of issue
