### ISSUE TITLE
Correct the game zone page and add some new features

### ISSUE THREAD

**Issue by sr-sweta** [arpit456jain/Cool-Front-End_Templates#75]
## Issue Type:

- [x] Bug Report
- [x] Feature Request
- [x] Documentation

## **Describe the bug**

The game zone page content is not placed well. And even more features can be added to the pages.

## **Possible solution**

I will place all content of game zone page well and will add more features to it. And will also add new features to other pages like footer, scroll top arrow.

## **Screenshots**

![Screenshot (790)](https://user-images.githubusercontent.com/70569920/125813910-9285c4bd-ad40-4f82-93a0-d4c2d1b39755.png)

**Comment by arpit456jain** [comment]
@sr-sweta go ahead

**Comment by arpit456jain** [comment]
@sr-sweta any updates

**Comment by sr-sweta** [comment]
Yes Game zone page is much better now . But I wanted to add some more
features to other pages and then I thought of doing the pr. Due to my exam
things are getting delayed. If you say I can pr now and latter on change
other pages.

**Comment by arpit456jain** [comment]
@sr-sweta make your PR now and for other changes create a new issue when u r free

**Comment by sr-sweta** [comment]
Ok sure. Thank you.

**Comment by arpit456jain** [comment]
@sr-sweta make your PR asap.
