### ISSUE TITLE
Add github pages website of this repository to readme

### ISSUE THREAD

**Issue by Dhruv-194** [arpit456jain/Cool-Front-End_Templates#79]
## Issue Type:

[ ] Bug Report
[x] Feature Request
[x] Documentaion

## **Describe the bug**

- I would be better if we could add the GitHub pages website of this repository to the readme so that people can easily view the projects of this repository. 
- It will act as a demo for this repository.

## **Possible solution**

- Kindly please share with me the GitHub pages website link so that I can add that to the README.md of this repository.

**Comment by arpit456jain** [comment]
Go ahead @Dhruv-194

**Comment by Dhruv-194** [comment]
> Go ahead @Dhruv-194

@arpit456jain kindly share with me the github pages website link for this repo so that I can add it

**Comment by arpit456jain** [comment]
https://arpit456jain.github.io/Cool-Front-End_Templates/

@Dhruv-194
