### ISSUE TITLE
Product Review Page

### ISSUE THREAD

**Issue by kiruba-r11** [arpit456jain/Cool-Front-End_Templates#80]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [] Documentaion

## **Possible solution**

- It is a responsive product review page that contains star ratings of the products, testimonials, etc.

## **Screenshots**
<img width="1346" alt="Screenshot 2021-07-17 at 10 49 19 AM" src="https://user-images.githubusercontent.com/76843281/126026681-e5c46cfa-058f-4233-b0de-9a75429b2173.png">

**Comment by kiruba-r11** [comment]
@ankitapuri @arpit456jain I would like to work on this as a part of DCP'21

**Comment by ankitapuri** [comment]
Ok go ahead
