### ISSUE TITLE
Add a Glassmorphism-Form 

### ISSUE THREAD

**Issue by siddhi-244** [arpit456jain/Cool-Front-End_Templates#82]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- I would like to add this template.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
@siddhi-244  i think it will come under Amazing-Css-Effects 
@ankitapuri your views?

**Comment by ankitapuri** [comment]
@siddhi-244 can please send any screenshot so that I can get an idea about what you are planning to make

**Comment by siddhi-244** [comment]
https://user-images.githubusercontent.com/69195262/126044331-4f78948d-1606-404d-8f0d-318cf0bb883b.mp4

**Comment by ankitapuri** [comment]
@arpit456jain I believe we can add it here

**Comment by arpit456jain** [comment]
Ok @ankitapuri 

@siddhi-244 go ahead
