### ISSUE TITLE
Fix bug in style_links.json

### ISSUE THREAD

**Issue by kiruba-r11** [arpit456jain/Cool-Front-End_Templates#84]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- There is a small bug in style_links.json file, due to which the page is not rendering.
- ScreenShot: 
<img width="536" alt="Screenshot 2021-07-18 at 11 53 53 AM" src="https://user-images.githubusercontent.com/76843281/126057847-2f1be4de-7922-4b25-a9de-135ef3ff55fa.png">

## **Possible solution**

- Adding a `comma on line 117` can solve this issue

**Comment by kiruba-r11** [comment]
@ankitapuri @arpit456jain I would like to work on this as a part of DCP'21

**Comment by ankitapuri** [comment]
@kiruba-r11 go ahead

**Comment by arpit456jain** [comment]
@kiruba-r11 kindly solve this issue asap
