### ISSUE TITLE
Furniture listing 

### ISSUE THREAD

**Issue by Naman-mahi** [arpit456jain/Cool-Front-End_Templates#90]
I would like to work on this project as it was listed in ideas. I would like to work under HCSSoC , DCP'21 and I request you to assign me this project.

**Comment by ankitapuri** [comment]
@Naman-mahi please explain a bit or attach a screenshot

**Comment by arpit456jain** [comment]
@Naman-mahi are you talking about making a template ?

**Comment by Naman-mahi** [comment]
![IMG-20210720-WA0003](https://user-images.githubusercontent.com/61780573/126498234-8d676f29-25a4-4add-994a-9d8c93419379.jpg)
![IMG-20210720-WA0004](https://user-images.githubusercontent.com/61780573/126498318-57a2af2c-f4eb-48e0-90ec-11f2fe44f5a8.jpg)

**Comment by Naman-mahi** [comment]
> @Naman-mahi are you talking about making a template ?

Yes, furniture product list

**Comment by arpit456jain** [comment]
Ok @Naman-mahi make sure you write your own code do not copy paste the code From anywhere

**Comment by Naman-mahi** [comment]
Yes sir, I write my own code and I'm full stack devloper

**Comment by Naman-mahi** [comment]
Please assign me

**Comment by arpit456jain** [comment]
ok @Naman-mahi go ahead

**Comment by arpit456jain** [comment]
@Naman-mahi see this issue is also open not completed yet try do complete it within 2 days

**Comment by arpit456jain** [comment]
@Naman-mahi create a new issue when your PR is ready
