### ISSUE TITLE
Improve UI of home page

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Cool-Front-End_Templates#97]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by jigar-sable** [comment]
I would like to work on this. Kindly assign me.
It's better to have preview of each template. I'm done with it, responsive too. Let me know if any changes. Images will be fetch from new JSON key called `preview`.

![cfet](https://user-images.githubusercontent.com/64949957/126902064-2b894682-3837-49d7-9080-de93e2e25b26.gif)

**Comment by arpit456jain** [comment]
ok @jigar-sable that's great 🎉🎉
